### ISSUE TITLE
窗口怎不支持调成一画面的吗？

### ISSUE THREAD

**Issue by potoo0** [tsingsee/EasyPlayer-RTSP-Win#14]
窗口怎不支持调成一画面的吗？
有四、八、九、十六画面，但是我目前只用得到一画面，其他三个画面占用窗口面积。请问有办法调成一画面的吗？谢谢啦

**Comment by Tsingsee-Seven** [comment]
可以啊，直接拿到代码改就可以了。


 
---原始邮件---
发件人: "potoo"<notifications@github.com&gt;
发送时间: 2020年4月18日(星期六) 下午4:27
收件人: "tsingsee/EasyPlayer-RTSP-Win"<EasyPlayer-RTSP-Win@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [tsingsee/EasyPlayer-RTSP-Win] 窗口怎不支持调成一画面的吗？ (#14)




 
窗口怎不支持调成一画面的吗？
 有四、八、九、十六画面，但是我目前只用得到一画面，其他三个画面占用窗口面积。请问有办法调成一画面的吗？谢谢啦

**Comment by potoo0** [comment]
您方便再给我指示下修改的位置吗？我不太懂 :)

**Comment by potoo0** [comment]
好的，谢谢您啦，我试试。

**Comment by potoo0** [comment]
您好，我修改好后，release 在本机上可以运行，但别的电脑运行就会出现 0x000007b 错误，而你们发布的 release 就可以使用，我查了一些链接器等属性的设置，但是不管用。
![image](https://user-images.githubusercontent.com/34411681/79681120-dcfccd00-8249-11ea-8761-1cf552d890c8.png)

**Comment by Tsingsee-Seven** [comment]
注意32位与64位的区别。


 
---原始邮件---
发件人: "potoo"<notifications@github.com&gt;
发送时间: 2020年4月19日(星期日) 下午2:28
收件人: "tsingsee/EasyPlayer-RTSP-Win"<EasyPlayer-RTSP-Win@noreply.github.com&gt;;
抄送: "Seven"<seven@easydarwin.org&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [tsingsee/EasyPlayer-RTSP-Win] 窗口怎不支持调成一画面的吗？ (#14)




 
您好，我修改好后，release 在本机上可以运行，但别的电脑运行就会出现 0x000007b 错误，而你们发布的 release 就可以使用，我查了一些链接器等属性的设置，但是不管用。
